name: my first GitHub Actions

on: [push]

jobs: 
  build: 
    run-on: ubuntu-latest

    strategy:
      matrix: 
        python-version: [3.8, 3.9]

    
    steps: 
    - uses: actions/checkout@v3
    - name: set up python
    with: 
      python-version: ${{ matirx.python-version }}
    
    -name: Install dependencies 
     run: |
       python -m pip install --upgrade pip 
       pip install pytest 
    
    -name: Run tests 
     run: |
       cd src 
       python -m pytest addition.py 